<a href="https://colab.research.google.com/github/qiaotracy33/LingRep/blob/main/WeeklyModules/Week05/Week05_Participation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import userdata
import os
import subprocess

github_token = userdata.get('Git_Key') #Retrieve secret key for user
owner = 'qiaotracy33' # Replace with the GitHub repository owner
repository = 'LingRep' # Replace with the GitHub repository name

clone_url = f'https://x-access-token:{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
import subprocess
subprocess.run(['git', 'clone', clone_url])

# Navigate into the cloned repository directory (optional, but often useful)
os.chdir(repository)
print(f"Changed directory to: {os.getcwd()}")

#!git clone https://github.com/"owner"/"repository".git for public repositories

Changed directory to: /content/LingRep/LingRep

In [5]:
#I do not have access to your drive.
#from google.colab import drive
#drive.mount('/content/drive')
#I updated the data patch to the file.
import pandas as pd
apple_csv = '/content/LingRep/data/aapl.csv'
amazon_csv = '/content/LingRep/data/amzn.csv'
google_csv = '/content/LingRep/data/goog.csv'
facebook_csv = '/content/LingRep/data/fb.csv'
netflix_csv = '/content/LingRep/data/nflx.csv'
apple_df = pd.read_csv(apple_csv)
amazon_df = pd.read_csv(amazon_csv)
google_df = pd.read_csv(google_csv)
facebook_df = pd.read_csv(facebook_csv)
netflix_df = pd.read_csv(netflix_csv)

In [6]:
apple_df["ticker"] = "AAPL"
amazon_df["ticker"] = "AMZN"
google_df["ticker"] = "GOOG"
facebook_df["ticker"] = "FB"
netflix_df["ticker"] = "NFLIX"

In [7]:
frames = []
frames.append(apple_df)
frames.append(amazon_df)
frames.append(google_df)
frames.append(facebook_df)
frames.append(netflix_df)

combined = pd.concat(frames, ignore_index=True)
combined.to_csv("faang.csv", index=False)         # e. 保存
combined.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [8]:
combined["date"] = pd.to_datetime(combined["date"])
combined["volume"] = combined["volume"].astype(int)
combined = combined.sort_values(by=["date", "ticker"])
combined.head()

           date       open       high        low      close    volume ticker
0    2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
251  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
753  2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
502  2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
1004 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889  NFLIX

In [9]:
top7 = combined.nlargest(n=7, columns=["volume"])
top7

          date      open      high       low     close     volume ticker
895 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
806 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
810 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
807 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [10]:
melted = combined.melt(id_vars=["date", "ticker"], value_vars=["open", "high", "low", "close", "volume"])
melted.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02  NFLIX     open   196.1000